# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: images/NgaPt.png
# Content configuration version
version: 2
# Personal info
name: Phạm Thị Nga
title: Computer Science | Trường ĐH Công nghệ Thông Tin - ĐHQG TPHCM
email: 21521168@gm.uit.edu.vn
# email_title: Email (Email title override)
phone: 0865128854
# phone_title: Phone (Phone title override)
website: https://github.com/venus9240/
# website_title: Web (Website title override)
# Dark Mode (true/false/never)
darkmode: false
# Social links
github_username:  venus9240
facebook_username: R9240
instagram_username: tn_9240
# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"
# About Section
about_title:  Chào bạn, cảm ơn vì đã click vào link này, và mình là một <mark>K16 UIT</mark>.
about_profile_image: images/avt.jpg
about_content:  | # this will include new lines to allow paragraphs
 Mọi người xung quanh quen với việc gọi mình là <mark>Thanh Nga</mark> 
 và nếu được bạn cũng gọi mình như thế nhé. Ngoài ra <mark>Venus</mark> 
 là tên mình sử dụng trong các tổ chức mà mình tham gia.
    - **MSSV:** 21521168
    - **Ngày sinh:** 30/03/2003
    - **Địa chỉ:** Tánh Linh, Bình Thuận
    - **Kĩ năng:** <mark>C++</mark>, <mark>Team building</mark> và *teamwork*.
content:
  - title: Lý tưởng sống
    layout: list
    content: 
      - layout: left
        title: Không ngừng cải thiện
        quote: >
          "Nếu mình nghĩ mình là cá mập thì phải bơi ngoài đại dương, cá ngừ, cá kiếm thì ngoài biển, cá rô, cá chép thì ra sông mà vẫy vùng."
        description: | # this will include new lines to allow paragraphs
          Ước mơ là một chuyện, năng lực là một chuyện khác. Trên hành trình sống của mỗi cá nhân đều là đang đi tìm **phiên bản hoàn hảo nhất** của chính mình, khẳng định được mình là ai, và mình có thể làm gì.
  - title: Trải nghiệm xã hội
    layout: list
    content:
      - layout: left
        title: Team building
        sub_title: Hoạt động xã hội & tổ chức chương trình khoá tu
        caption: 2017 và sẽ tới khi không còn có thể
        quote: >
          "Tuổi trẻ là cháy hết mình với đam mê, cống hiến để trưởng thành."
        description: | # this will include new lines to allow paragraphs
          Với lợi thế là sự nhiệt huyết của tuổi trẻ, team chúng mình với các thành viên đủ mọi lứa tuổi luôn *sẵn sàng trong mọi tình huống, làm mọi việc có thể* với hi vọng đem đến tiếng cười và niềm vui cho những người đang thiếu. Tuổi trẻ là cháy hết mình với đam mê, cống hiến cho cộng đồng với hi vọng phủ một gam màu tích cực lên cuộc sống đầy khó khăn thử thách.
  - title: Trình độ học vấn
    layout: list
    content:
      - layout: left
        title: VNUHCM-University of Information Technology
        sub_title: Cử nhân ngành Khoa học Máy tính
        caption: 2021-2025
        quote: >
           "Xuất phát điểm có thể thấp nhưng không thể quyết định đích đến." 
        description: | # this will include new lines to allow paragraphs
          Là trường thành viên của ĐHQG-HCM, trường ĐH CNTT có nhiệm vụ đào tạo nguồn nhân lực công nghệ thông tin chất lượng cao, góp phần tích cực vào sự phát triển của nền công nghiệp công nghệ thông tin Việt Nam, đồng thời tiến hành nghiên cứu khoa học và chuyển giao công nghệ thông tin tiên tiến, đặc biệt là hướng vào các ứng dụng nhằm góp phần đẩy mạnh sự nghiệp công nghiệp hóa, hiện đại hóa đất nước.
  - title: Một chút ngoài lề nho nhỏ về mình
    layout: text
    content: | # this will include new lines to allow paragraphs
      Mỗi người có những sở thích riêng, để giết thời gian, yêu chiều bản thân hay chỉ đơn giản là kéo bản thân lên từ hố đen trống rỗng trong tâm hồn
      - Đọc sách
      - League of legends, CS:Go
      - Tìm hiểu về vũ trụ, thiên hà
      - Nghiên cứu tâm lý học hành vi
      
      
# Footer
footer_show_references: true
# references_title: References on request (Override references text)
# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)
