# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Phạm Thị Nga
title: Computer Science | Trường ĐH Công nghệ Thông Tin - ĐHQG TPHCM
email: 21521168@gm.uit.edu.vn
# email_title: Email (Email title override)
phone: 0865128854
# phone_title: Phone (Phone title override)
website: https://github.com/venus9240/
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  venus9240
facebook_username: R9240
instagram_username: tn_9240


# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: Chào bạn, cảm ơn vì đã click vào link này, và mình là Phạm Thị Nga
about_profile_image: Directory of profile image (eg. images/profile.jpg)
about_content: | # this will include new lines to allow paragraphs
 Chào bạn, cảm ơn vì đã click vào link này, và mình là một <mark>K16 UIT</mark>. 
 Mọi người xung quanh quen với việc gọi mình là <mark>Thanh Nga</mark> 
 và nếu được bạn cũng gọi mình như thế nhé. Ngoài ra <mark>Venus</mark> 
 là tên mình sử dụng trong các tổ chức mà mình tham gia.
    - MSSV : 21521168
    - Ngày sinh : 30/03/2003
    - Địa chỉ : Tánh Linh, Bình Thuận
    -  Kĩ năng: <mark>C++</mark> and <mark>Team building</mark>
content:
  - title: Lý tưởng sống # Title for the section
      - layout: left
        title: Lý lịch bản thân trong sạch Phẩm chất đạo đức vững vàng Lý luận chính trị không ngừng nâng cao
        quote: >
          Short overview of the project (optional)
        description: | # this will include new lines to allow paragraphs
          Description about the work on/with the project
  - title: Experience
    layout: list
    content:
      - layout: right
        title: Company name
        sub_title: Job title
        caption: Date Range (eg. November 2016 - present)
        link: Link to company (optional)
        quote: >
          Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          Description of role
  - title: Education
    layout: list
    content:
      - layout: top-right
        title: Institution name
        sub_title: Qualifications (eg. BA Performing Arts)
        caption: Date Range (eg. 2016 - 2019)
        quote: >
          Short institution or course description (optional)
        description: | # this will include new lines to allow paragraphs
          Description of qualification
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      This is where you can write a little more about yourself. You could title this section **Interests** and include some of your other interests.

      Or you could title it **Skills** and write a bit more about things that make you more desirable, like *leadership* or *teamwork*

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
